/* CASPER — standalone sector archive renderer. It intentionally reads ONLY the sector archive. */
(function(){
  'use strict';
  var root=(window.CASPER_PAGE&&window.CASPER_PAGE.root)||'../';
  var sectorId=(window.CASPER_PAGE&&window.CASPER_PAGE.sector)||'sector-1';
  var app=document.getElementById('sector-app');
  var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  function empty(msg){app.innerHTML='<div class="sector-wrap"><div class="sector-card"><div class="sector-muted">'+esc(msg)+'</div></div></div>';}
  function load(path){return fetch(root+path+'?v=20260910sector2').then(function(r){if(!r.ok)throw Error('Could not load '+path);return r.json();});}
  function parseFiles(files){var all=[],p=Promise.resolve();(files||[]).forEach(function(f){p=p.then(function(){return fetch(root+'data/sectors/'+sectorId+'/'+f+'?v=20260910sector2').then(function(r){return r.ok?r.text():'';}).then(function(text){if(text&&typeof parseCSN==='function')all.push.apply(all,parseCSN(text)||[]);});});});return p.then(function(){return all;});}
  function sportOf(t){var x=(t&&t.meta)||{};var fmt=String(x.fmt||'').toLowerCase();if(x.id&&/^tc/i.test(x.id))return 'cricket';if(/cricket|innings|ball/.test(fmt))return 'cricket';if(/futsal/.test(String(x.sport||'').toLowerCase()))return 'futsal';if(/football|soccer/.test(String(x.sport||'').toLowerCase()))return 'football';return null;}
  function score(m,sport){if(sport==='cricket')return (m.sh||0)+'/'+(m.hw||0)+' – '+(m.sa||0)+'/'+(m.aw||0);return (m.sh||0)+'–'+(m.sa||0);}
  function result(m){if(m.p)return m.p[0]>m.p[1]?'H':m.p[0]<m.p[1]?'A':'D';return m.sh>m.sa?'H':m.sh<m.sa?'A':'D';}
  function nameOf(t,code){return t&&t.n&&t.n[code]&&t.n[code].name||code;}
  function sportLabel(s){return s==='futsal'?'Futsal':s==='football'?'Football':'Cricket';}
  function goalEvents(matches){var out={};matches.forEach(function(x){[].concat(x.m.gh||[],x.m.ga||[]).forEach(function(g){var k=String(g.name||'').replace(/\(.*?\)/g,'').trim();if(!k)return;if(!out[k])out[k]={name:k,goals:0};out[k].goals+=Number(g.n)||0;});});return Object.values(out).sort(function(a,b){return b.goals-a.goals||a.name.localeCompare(b.name);});}
  function renderGoalCard(title,matches){var top=goalEvents(matches).slice(0,8);var rows=top.map(function(p){return '<tr><td>'+esc(p.name)+'</td><td>'+p.goals+'</td></tr>';}).join('')||'<tr><td colspan="2" class="sector-muted">No goal events are logged in this sector yet.</td></tr>';return '<div class="sector-card"><h3>'+esc(title)+' · Sector tally</h3><table class="sector-table"><thead><tr><th>Player</th><th>Goals</th></tr></thead><tbody>'+rows+'</tbody></table><div class="sector-footer">Only logged '+esc(title.toLowerCase())+' goal events are counted. Career totals are not used.</div></div>';}
  function renderCricketCard(matches){var teams={};matches.forEach(function(x){var m=x.m;var h=m.home,a=m.away;if(!teams[h])teams[h]={name:nameOf(x.t,h),runs:0,wicketsTaken:0};if(!teams[a])teams[a]={name:nameOf(x.t,a),runs:0,wicketsTaken:0};teams[h].runs+=Number(m.sh)||0;teams[a].runs+=Number(m.sa)||0;teams[h].wicketsTaken+=Number(m.aw)||0;teams[a].wicketsTaken+=Number(m.hw)||0;});var rows=Object.keys(teams).map(function(k){return teams[k];}).sort(function(a,b){return b.runs-a.runs||b.wicketsTaken-a.wicketsTaken||a.name.localeCompare(b.name);}).map(function(x){return '<tr><td>'+esc(x.name)+'</td><td>'+x.runs+'</td><td>'+x.wicketsTaken+'</td></tr>';}).join('')||'<tr><td colspan="3" class="sector-muted">No cricket results are logged in this sector yet.</td></tr>';return '<div class="sector-card"><h3>Cricket · Sector tally</h3><table class="sector-table"><thead><tr><th>Club</th><th>Runs</th><th>Wkts</th></tr></thead><tbody>'+rows+'</tbody></table><div class="sector-footer">Cricket runs are team runs scored. Wickets are wickets taken from the opponent. No football/futsal goal tally is mixed into cricket.</div></div>';}
  function render(sector,tours){
    var comps=tours.filter(function(t){return t.meta&&t.meta.id;});
    var clubSet={};(sector.clubCodes||[]).forEach(function(c){clubSet[String(c).toLowerCase()]=c;});
    var matches=[];comps.forEach(function(t){var sport=sportOf(t);(t.m||[]).forEach(function(m){if(clubSet[String(m.home).toLowerCase()]&&clubSet[String(m.away).toLowerCase()])matches.push({m:m,t:t,sport:sport});});});
    var clubs={};(sector.clubCodes||[]).forEach(function(code){clubs[code]={code:code,name:code.toUpperCase(),p:0,w:0,d:0,l:0,gf:0,ga:0};});
    comps.forEach(function(t){Object.keys(t.n||{}).forEach(function(c){if(clubSet[String(c).toLowerCase()])clubs[clubSet[String(c).toLowerCase()]].name=t.n[c].name||c;});});
    matches.filter(function(x){return x.sport!=='cricket';}).forEach(function(x){var m=x.m,h=clubSet[String(m.home).toLowerCase()],a=clubSet[String(m.away).toLowerCase()];if(!clubs[h]||!clubs[a])return;clubs[h].gf+=m.sh||0;clubs[h].ga+=m.sa||0;clubs[a].gf+=m.sa||0;clubs[a].ga+=m.sh||0;var r=result(m);if(r==='H'){clubs[h].w++;clubs[a].l++;clubs[h].p+=3;}else if(r==='A'){clubs[a].w++;clubs[h].l++;clubs[a].p+=3;}else{clubs[h].d++;clubs[a].d++;clubs[h].p++;clubs[a].p++;}});
    var standings=Object.values(clubs).sort(function(a,b){return b.p-a.p||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||a.name.localeCompare(b.name);});
    var bySport={futsal:[],football:[],cricket:[]};matches.forEach(function(x){if(bySport[x.sport])bySport[x.sport].push(x);});
    var sportMatches=bySport.futsal.length+bySport.football.length+bySport.cricket.length;
    var futsalGoals=goalEvents(bySport.futsal).reduce(function(s,p){return s+p.goals;},0),footballGoals=goalEvents(bySport.football).reduce(function(s,p){return s+p.goals;},0);
    var cricketRuns=bySport.cricket.reduce(function(s,x){return s+(Number(x.m.sh)||0)+(Number(x.m.sa)||0);},0),cricketWickets=bySport.cricket.reduce(function(s,x){return s+(Number(x.m.hw)||0)+(Number(x.m.aw)||0);},0);
    var leagueHtml=(sector.leagues||[]).map(function(l){return '<div class="sector-league"><b>'+esc(l.name)+'</b><span class="sector-muted">'+esc(l.sport||'')+' · '+esc(l.season||'')+'</span></div>';}).join('')||'<div class="sector-muted">No leagues registered.</div>';
    var clubHtml=standings.map(function(c){return '<div class="sector-club"><b>'+esc(c.name)+'</b><span>'+esc(c.code)+' · '+(c.w+c.d+c.l)+' matches</span></div>';}).join('')||'<div class="sector-muted">No clubs registered.</div>';
    var resultHtml=matches.slice().reverse().slice(0,10).map(function(x){var m=x.m;return '<div class="sector-row"><span><b>'+esc(nameOf(x.t,m.home))+'</b> <span class="sector-muted">vs</span> <b>'+esc(nameOf(x.t,m.away))+'</b></span><span class="sector-score">'+esc(score(m,x.sport))+'</span><span class="sector-pill">'+esc((x.t.meta&&x.t.meta.e)||x.t.meta.id)+'</span></div>';}).join('')||'<div class="sector-empty sector-muted">No results logged yet.</div>';
    var sportCards='';if(bySport.futsal.length||((sector.sports||[]).indexOf('futsal')>=0))sportCards+=renderGoalCard('Futsal goals',bySport.futsal);if(bySport.football.length||((sector.sports||[]).indexOf('football')>=0))sportCards+=renderGoalCard('Football goals',bySport.football);if(bySport.cricket.length||((sector.sports||[]).indexOf('cricket')>=0))sportCards+=renderCricketCard(bySport.cricket);
    var tableHtml=standings.map(function(c,i){return '<tr><td>'+((i+1))+'</td><td>'+esc(c.name)+'</td><td>'+c.p+'</td><td>'+(c.gf-c.ga>0?'+':'')+(c.gf-c.ga)+'</td><td>'+c.gf+'</td></tr>';}).join('');
    var stats='<div class="sector-stat"><b>'+standings.length+'</b><span>CLUBS</span></div><div class="sector-stat"><b>'+sportMatches+'</b><span>MATCHES</span></div><div class="sector-stat"><b>'+comps.length+'</b><span>COMPETITIONS</span></div>';
    if(bySport.futsal.length||((sector.sports||[]).indexOf('futsal')>=0))stats+='<div class="sector-stat"><b>'+futsalGoals+'</b><span>FUTSAL GOALS</span></div>';
    if(bySport.football.length||((sector.sports||[]).indexOf('football')>=0))stats+='<div class="sector-stat"><b>'+footballGoals+'</b><span>FOOTBALL GOALS</span></div>';
    if(bySport.cricket.length||((sector.sports||[]).indexOf('cricket')>=0)){stats+='<div class="sector-stat"><b>'+cricketRuns+'</b><span>CRICKET RUNS</span></div><div class="sector-stat"><b>'+cricketWickets+'</b><span>CRICKET WICKETS</span></div>';}
    app.innerHTML='<div class="sector-wrap">'+
      '<div class="sector-top"><div><div class="sector-kicker">CASPER SECTOR · '+esc(sector.code||sectorId)+'</div><h1 class="sector-title">'+esc(sector.name||sectorId)+'</h1><p class="sector-desc">'+esc(sector.description||'Local competitive ecosystem.')+'</p></div><a class="sector-back" href="index.html">← All Sectors</a></div>'+ 
      '<div class="sector-stats">'+stats+'</div>'+ 
      '<div class="sector-grid"><div><div class="sector-card"><h3>Standings</h3><table class="sector-table"><thead><tr><th>#</th><th>Club</th><th>Pts</th><th>GD</th><th>GF</th></tr></thead><tbody>'+tableHtml+'</tbody></table></div><div class="sector-card"><h3>Recent Results</h3>'+resultHtml+'</div></div><div><div class="sector-card"><h3>Sector Leagues</h3>'+leagueHtml+'</div><div class="sector-card"><h3>Clubs</h3><div class="sector-clubs">'+clubHtml+'</div></div>'+sportCards+'</div></div>'+ 
      '<div class="sector-footer">'+esc(sector.name||sectorId)+' · '+esc(sector.status||'Active')+' · '+esc((sector.seasons||[]).join(', '))+'</div></div>';
  }
  Promise.all([load('sectors.json')]).then(function(p){var reg=p[0]||{},sector=(reg.sectors||[]).find(function(s){return s.id===sectorId;});if(!sector)throw Error('Sector not found: '+sectorId);var manifestPath=(sector.archive&&sector.archive.manifest)||('data/sectors/'+sectorId+'/manifest.json');return load(manifestPath).then(function(manifest){return parseFiles(manifest.files||manifest.seasons||[]).then(function(tours){render(sector,tours);});});}).catch(function(e){empty(e.message||'Sector archive failed to load.');});
})();
